[project]
name = "kokoro-tts-mcp"
version = "0.1.0"
description = "Kokoro Text to Speech (TTS) MCP Server"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "kokoro-onnx>=0.4.5",
    "soundfile>=0.13.1",
]
